export default {
  account: 'user',
  // 'activate-breakpoints': '',
  add: 'plus',
  alert: 'alert-triangle',
  archive: 'archive',
  // 'array': '',
  // 'arrow-both': '',
  'arrow-down': 'arrow-down',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  // 'arrow-small-down': '',
  // 'arrow-small-left': '',
  // 'arrow-small-right': '',
  // 'arrow-small-up': '',
  'arrow-up': 'arrow-up',
  // beaker: '',
  bell: 'bell',
  // 'bell-dot': '',
  bold: 'bold',
  book: 'book-open',
  bookmark: 'bookmark',
  briefcase: 'briefcase',
  broadcast: 'cast',
  // browser: '',
  // bug: '',
  calendar: 'calendar',
  'call-incoming': 'phone-incoming',
  'call-outgoing': 'phone-outgoing',
  // 'case-sensitive': '',
  check: 'check',
  // 'check-all': '',
  // checklist: '',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'chrome-close': 'x',
  'chrome-maximize': 'square',
  'chrome-minimize': 'minus',
  'chrome-restore': 'copy',
  // 'circle-filled': '',
  // 'circle-large-filled': '',
  // 'circle-large-outline': '',
  // 'circle-outline': '',
  // 'circle-slash': '',
  'circuit-board': 'cpu',
  // 'clear-all': '',
  // 'clippy': '',
  clock: 'clock',
  clone: 'copy',
  // close: 'x',
  // 'close-all': '',
  // 'close-dirty': '',
  cloud: 'cloud',
  'cloud-download': 'download-cloud',
  'cloud-upload': 'upload-cloud',
  code: 'code',
  'collapse-all': 'folder-minus',
  // 'color-mode': '',
  // 'combine': '',
  comment: 'message-square',
  'comment-add': 'message-square',
  // 'comment-discussion': '',
  // 'compare-changes': '',
  console: 'terminal',
  'credit-card': 'credit-card',
  // 'dash': '',
  // dashboard: '',
  database: 'database',
  // debug: '',
  // 'debug-alt': '',
  // 'debug-alt-small': '',
  // 'debug-breakpoint': '',
  // 'debug-breakpoint-conditional': '',
  // 'debug-breakpoint-conditional-disabled': '',
  // 'debug-breakpoint-conditional-unverified': '',
  // 'debug-breakpoint-data': '',
  // 'debug-breakpoint-data-disabled': '',
  // 'debug-breakpoint-data-unverified': '',
  // 'debug-breakpoint-disabled': '',
  // 'debug-breakpoint-function': '',
  // 'debug-breakpoint-function-disabled': '',
  // 'debug-breakpoint-function-unverified': '',
  // 'debug-breakpoint-log': '',
  // 'debug-breakpoint-log-disabled': '',
  // 'debug-breakpoint-log-unverified': '',
  // 'debug-breakpoint-unsupported': '',
  // 'debug-breakpoint-unverified': '',
  // 'debug-console': '',
  // 'debug-continue': '',
  // 'debug-disconnect': '',
  // 'debug-hint': '',
  // 'debug-line-by-line': ''
  // 'debug-pause': '',
  // 'debug-rerun': '',
  // 'debug-restart': '',
  // 'debug-restart-frame': '',
  // 'debug-reverse-continue': '',
  // 'debug-stackframe': '',
  // 'debug-stackframe-active': '',
  // 'debug-stackframe-dot': '',
  // 'debug-stackframe-focused': '',
  // 'debug-start': '',
  // 'debug-step-back': '',
  // 'debug-step-into': '',
  // 'debug-step-out': '',
  // 'debug-step-over': '',
  // 'debug-stop': '',
  // 'desktop-download': '',
  'device-camera': 'camera',
  'device-camera-video': 'video',
  'device-desktop': 'monitor',
  // 'device-mobile': '',
  // 'diff': '',
  // 'diff-added': '',
  // 'diff-ignored': '',
  // 'diff-modified': '',
  // 'diff-removed': '',
  // 'diff-renamed': '',
  discard: 'corner-up-left',
  // 'drop-down-button': '',
  edit: 'edit',
  // 'editor-layout': '',
  ellipsis: 'more-horizontal',
  // 'empty-window': '',
  error: 'x-circle',
  // 'exclude': '',
  // 'expand-all': '',
  export: 'send',
  extensions: 'box',
  eye: 'eye',
  'eye-closed': 'eye-off',
  'eye-unwatch': 'eye',
  'eye-watch': 'eye',
  feedback: 'message-circle',
  // 'file': '',
  // 'file-add': '',
  // 'file-binary': '',
  // 'file-code': '',
  // 'file-directory': '',
  // 'file-directory-create': '',
  // 'file-media': '',
  // 'file-pdf': '',
  // 'file-submodule': '',
  // 'file-symlink-directory': '',
  // 'file-symlink-file': '',
  // 'file-text': '',
  // 'file-zip': '',
  // files: '',
  filter: 'filter',
  // flame: '',
  // 'fold': '',
  'fold-down': 'chevrons-down',
  'fold-up': 'chevrons-up',
  // 'folder': '',
  // 'folder-active': '',
  // 'folder-opened': '',
  // 'gather': '',
  gear: 'settings',
  gift: 'gift',
  // gist: '',
  // 'gist-fork': '',
  // 'gist-new': '',
  // 'gist-private': '',
  // 'gist-secret': '',
  'git-branch': 'git-branch',
  'git-branch-create': 'git-branch',
  'git-branch-delete': 'git-branch',
  'git-commit': 'git-commit',
  // 'git-compare': '',
  'git-fork-private': 'lock',
  'git-merge': 'git-merge',
  'git-pull-request': 'git-pull-request',
  'git-pull-request-abandoned': 'git-pull-request',
  'git-pull-request-create': 'git-pull-request',
  github: 'github',
  'github-action': 'github',
  'github-alt': 'github',
  'github-inverted': 'github',
  globe: 'globe',
  // 'go-to-file': '',
  // 'grabber': '',
  // 'graph': '',
  // 'graph-left': '',
  // 'gripper': '',
  // 'group-by-ref-type': '',
  heart: 'heart',
  history: 'clock',
  home: 'home',
  // 'horizontal-rule': '',
  // hubot: '',
  inbox: 'inbox',
  info: 'info',
  // 'issue-closed': '',
  // 'issue-opened': '',
  // 'issue-reopened': '',
  // 'issues': '',
  italic: 'italic',
  // 'jersey': '',
  // json: '',
  'kebab-horizontal': 'more-horizontal',
  'kebab-vertical': 'more-vertical',
  key: 'key',
  // keyboard: '',
  // law: '',
  // 'library': '',
  // 'light-bulb': '',
  // lightbulb: '',
  // 'lightbulb-autofix': '',
  link: 'link',
  'link-external': 'external-link',
  // 'list-filter': '',
  // 'list-flat': '',
  // 'list-ordered': '',
  // 'list-selection': '',
  // 'list-tree': '',
  // 'list-unordered': '',
  'live-share': 'share-2',
  loading: 'loader',
  location: 'map-pin',
  lock: 'lock',
  'log-in': 'log-in',
  'log-out': 'log-out',
  'logo-github': 'github',
  // 'magnet': '',
  mail: 'mail',
  'mail-read': 'file',
  'mail-reply': 'corner-up-left',
  'mark-github': 'github',
  // 'markdown': '',
  // megaphone: '',
  mention: 'at-sign',
  menu: 'menu',
  // merge: '',
  // microscope: '',
  // milestone: '',
  // 'mirror': '',
  // 'mirror-private': '',
  // 'mirror-public': '',
  more: 'more-horizontal',
  // 'mortar-board': '',
  move: 'move',
  // 'multiple-windows': '',
  mute: 'volume-x',
  'new-file': 'file-plus',
  'new-folder': 'folder-plus',
  // 'no-newline': '',
  // 'note': '',
  // 'notebook': '',
  // 'notebook-template': '',
  // 'octoface': '',
  // 'open-preview': '',
  organization: 'users',
  'organization-filled': 'users',
  'organization-outline': 'users',
  // 'output': '',
  package: 'package',
  // 'paintcan': '',
  pass: 'check-circle',
  'pass-filled': 'check-circle',
  pencil: 'edit-2',
  // person: '',
  // 'person-add': '',
  // 'person-filled': '',
  // 'person-follow': '',
  // 'person-outline': '',
  // 'pin': '',
  // 'pinned': '',
  // 'pinned-dirty': '',
  play: 'play',
  'play-circle': 'play-circle',
  // plug: '',
  plus: 'plus',
  // 'preserve-case': '',
  // 'preview': '',
  // 'primitive-dot': '',
  // 'primitive-square': '',
  // 'project': '',
  pulse: 'activity',
  question: 'help-circle',
  // quote: '',
  'radio-tower': 'radio',
  // reactions: '',
  // 'record': '',
  // 'record-keys': '',
  redo: 'corner-up-right',
  // 'references': '',
  refresh: 'refresh-cw',
  // 'regex': '',
  remote: 'airplay',
  'remote-explorer': 'airplay',
  // 'remove': '',
  // 'remove-close': '',
  repl: 'terminal',
  // 'replace': '',
  // 'replace-all': '',
  reply: 'corner-up-left',
  // 'repo': '',
  // 'repo-clone': '',
  // 'repo-create': '',
  // 'repo-delete': '',
  // 'repo-force-push': '',
  // 'repo-forked': '',
  // 'repo-pull': '',
  // 'repo-push': '',
  // 'repo-sync': '',
  // 'report': '',
  // 'request-changes': '',
  // rocket: '',
  // 'root-folder': '',
  // 'root-folder-opened': '',
  rss: 'rss',
  // 'ruby': '',
  // 'run': '',
  // 'run-all': '',
  // 'run-above': '',
  // 'run-below': '',
  // save: '',
  // 'save-all': '',
  // 'save-as': '',
  'screen-full': 'maximize',
  'screen-normal': 'minimize',
  search: 'search',
  'search-save': 'search',
  // 'search-stop': '',
  // 'selection': '',
  server: 'server',
  'server-environment': 'server',
  'server-process': 'server',
  settings: 'sliders',
  'settings-gear': 'settings',
  shield: 'shield',
  'sign-in': 'log-in',
  'sign-out': 'log-out',
  smiley: 'smile',
  // 'sort-precedence': '',
  'source-control': 'git-branch',
  // 'split-horizontal': '',
  // 'split-vertical': '',
  // 'squirrel': '',
  star: 'star',
  'star-add': 'star',
  'star-delete': 'star',
  'star-empty': 'star',
  // 'star-full': '',
  // 'star-half': '',
  stop: 'x-circle',
  'stop-circle': 'stop-circle',
  // 'symbol-array': '',
  // 'symbol-boolean': '',
  // 'symbol-class': '',
  // 'symbol-color': '',
  // 'symbol-constant': '',
  // 'symbol-constructor': '',
  // 'symbol-enum': '',
  // 'symbol-enum-member': '',
  // 'symbol-event': '',
  // 'symbol-field': '',
  // 'symbol-file': '',
  // 'symbol-folder': '',
  // 'symbol-function': '',
  // 'symbol-interface': '',
  // 'symbol-key': '',
  // 'symbol-keyword': '',
  // 'symbol-method': '',
  // 'symbol-misc': '',
  // 'symbol-module': '',
  // 'symbol-namespace': '',
  // 'symbol-null': '',
  // 'symbol-number': '',
  // 'symbol-numeric': '',
  // 'symbol-object': '',
  // 'symbol-operator': '',
  // 'symbol-package': '',
  // 'symbol-parameter': '',
  // 'symbol-property': '',
  // 'symbol-reference': '',
  // 'symbol-ruler': '',
  // 'symbol-snippet': '',
  // 'symbol-string': '',
  // 'symbol-struct': '',
  // 'symbol-structure': '',
  // 'symbol-text': '',
  // 'symbol-type-parameter': '',
  // 'symbol-unit': '',
  // 'symbol-value': '',
  // 'symbol-variable': '3d-mpr-toggle',
  // 'sync': '',
  // 'sync-ignored': '',
  tag: 'tag',
  'tag-add': 'tag',
  'tag-remove': 'tag',
  // tasklist: '',
  // 'telescope': '',
  terminal: 'terminal',
  // 'text-size': '',
  // 'three-bars': '',
  thumbsdown: 'thumbs-down',
  thumbsup: 'thumbs-up',
  tools: 'tool',
  trash: 'trash',
  trashcan: 'trash',
  // 'triangle-down': '',
  // 'triangle-left': '',
  // 'triangle-right': '',
  // 'triangle-up': '',
  twitter: 'twitter',
  // 'type-hierarchy': '',
  // 'type-hierarchy-sub': '',
  // 'type-hierarchy-super': '',
  // 'unfold': '',
  // 'ungroup-by-ref-type': '',
  unlock: 'unlock',
  unmute: 'volume-2',
  // 'unverified': '',
  // variable: '',
  // 'verified': '',
  // versions: '',
  // 'vm': '',
  // 'vm-active': '',
  // 'vm-connect': '',
  // 'vm-outline': '',
  // 'vm-running': '',
  warning: 'alert-triangle',
  watch: 'watch',
  // whitespace: '',
  // 'whole-word': '',
  // 'window': '',
  // 'word-wrap': '',
  wrench: 'tool',
  'wrench-subaction': 'tool',
  x: 'x',
  zap: 'zap',
  'zoom-in': 'zoom-in',
  'zoom-out': 'zoom-out'
};
